export const EndPoints = {
  pixCreateCharge: 'pixCreateCharge',
  pixUpdateCharge: 'pixUpdateCharge',
  pixCreateImmediateCharge: 'pixCreateImmediateCharge',
  pixDetailCharge: 'pixDetailCharge',
  pixListCharges: 'pixListCharges',
  pixDetail: 'pixDetail',
  pixListReceived: 'pixListReceived',
  pixSend: 'pixSend',
  pixDevolution: 'pixDevolution',
  pixDetailDevolution: 'pixDetailDevolution',
  pixConfigWebhook: 'pixConfigWebhook',
  pixDetailWebhook: 'pixDetailWebhook',
  pixListWebhook: 'pixListWebhook',
  pixDeleteWebhook: 'pixDeleteWebhook',
  pixCreateLocation: 'pixCreateLocation',
  pixListLocation: 'pixListLocation',
  pixDetailLocation: 'pixDetailLocation',
  pixGenerateQRCode: 'pixGenerateQRCode',
  pixUnsetTxid: 'pixUnsetTxid',
  gnCreateEvp: 'gnCreateEvp',
  gnListEvp: 'gnListEvp',
  gnDeleteEvp: 'gnDeleteEvp',
  gnDetailBalance: 'gnDetailBalance',
  gnUpdateSettings: 'gnUpdateSettings',
  gnDetailSettings: 'gnDetailSettings',
};
