SELECT CodProcessoExecutavel,
  CodEmpresa,
  CodFilial,
  Status,
  Contexto,
  Origem,
  CodOrigem,
  ItemOrigem,
  DataAbertura,
  CodUsuario,
  NomeUsuario,
  CodContaFinanceira,
  CodPeriodoCaixa,
  StatusPeriodoCaixa,
  UsuarioWindows,
  NomeComputador,
  BancoDados
FROM ProcessoExecutavel