
GET http://localhost:3000/cobranca HTTP/1.1

###

POST http://localhost:3000/cobranca HTTP/1.1
content-type: application/json

//open charge
{
	"Data": [
		{
			"Id": "dsjkskfjkgisakkakd34353",
			"LiberacaoKey": {
				"IdLiberacao": "ofdkjdfasfakfakfkadf99",
				"CodEmpresa": 1,
				"CodFilial": 1,
				"Origem": "OB",
				"CodOrigem": 777,
				"Item": "001"
			},
			"Usuario": {
				"CodUsuario": 34,
				"NomeUsuario": "ADMINISTRADOR",
				"EstacaoTrabalho": "SERVIDOR",
				"IP": "0.0.0.0"
			},
			"Filial": {
				"CodEmpresa": 1,
				"CodFilial": 1,
				"Nome": "SE7E SISTEMAS",
				"CNPJ": "00000000000"
			},
			"Cliente": {
				"CodCliente": 23452,
				"NomeCliente": "CLIENTE TESTE",
				"CNPJ_CPF": "55060958051",
				"Telefone": "00 00000-0000",
				"EMail": "email@teste.com",
				"Endereco": "ENDERECO",
				"Numero": "SN",
				"Complemento": "COMPLEMENTO",
				"Bairro": "BAIRRO",
				"CEP": "78555555",
				"CodigoIBGE": "11111111",
				"NomeMunicipio": "SINOP",
				"UF": "MT"
			},
			"Parcelas": [
				{
					"Origem": "OB",
					"CodOrigem": 777,
					"NumeroParcela": "001/001",
					"CodFormaPagamento": "PIX",
					"DataEmissao": "2020-01-01",
					"DataVenda": "2020-01-01",
					"DataVencimento": "2020-01-01",
					"ValorBruto": 0.50,
					"ValorLiquido": 0.50,
					"ValorParcela": 0.50,
					"Observacao": "OBs PARCELA INF"
				}
			]
		}
	]
}
