
GET http://localhost:3000/webhook HTTP/1.1

###

POST http://localhost:3000/webhook HTTP/1.1
content-type: application/json

{
    "cnpj_cpf": "05942151000182",
    "chave": "bc89689b-11bc-4304-b2c4-c474e90e2467",
    "url": "https://api.se7sistemas.com/webhook"
}
