export enum STATUS {
  ATIVO = 'ATIVO',
  DEVOLVIDO = 'DEVOLVIDO',
  CANCELADO = 'CANCELADO',
  CONCLUIDO = 'CONCLUIDO',
  FINALIZADO = 'FINALIZADO',
  RECUSADO = 'RECUSADO',
  CANCELADO_SISTEMA = 'CANCELADO-SISTEMA',
  CANCELADO_CLIENTE = 'CANCELADO-CLIENTE',
  MONTANDO_COBRANCA = 'MONTANDO-COBRANCA',
  AGUARDANDO = 'AGUARDANDO',
  MENSAGEM_BLOQUEIO = 'PIX AGUARDE CONFIRMACAO DE PAGAMENTO',
}
