export enum STATUS {
  ATIVO = 'ATIVO', // AGARDANDO PAGAMENTO
  DEVOLVIDO = 'DEVOLVIDO', // VALOR ESTORNADO
  CANCELADO = 'CANCELADO', // CANCELADO REGRA OU OUVINTE
  CONCLUIDO = 'CONCLUIDO', // PAGAMENTO FINALIZADO
  CANCELADO_SISTEMA = 'CANCELADO-SISTEMA',
  CANCELADO_CLIENTE = 'CANCELADO-CLIENTE',
  RECUSADO = 'RECUSADO',
  FINALIZADO = 'FINALIZADO', // PROCESSO LIBERADO
}
