SELECT CodEmpresa,
  CodSepararEstoque,
  CodTipoOperacaoExpedicao,
  TipoEntidade,
  CodEntidade,
  NomeEntidade,
  Situacao,
  Data,
  Hora,
  CodPrioridade,
  Historico,
  Observacao,
  CodMotivoCancelamento,
  DataCancelamento,
  HoraCancelamento,
  CodUsuarioCancelamento,
  NomeUsuarioCancelamento,
  ObservacaoCancelamento
FROM Expedicao.SepararEstoque