INSERT INTO Expedicao.ItemSepararEstoque(
    CodEmpresa,
    CodSepararEstoque,
    Item,
    CodSetorEstoque,
    Origem,
    CodOrigem,
    ItemOrigem,
    CodLocaArmazenagem,
    CodProduto,
    CodUnidadeMedida,
    Quantidade,
    QuantidadeInterna,
    QuantidadeExterna,
    QuantidadeSeparacao
  )
VALUES (
    @CodEmpresa,
    @CodSepararEstoque,
    @Item,
    @CodSetorEstoque,
    @Origem,
    @CodOrigem,
    @ItemOrigem,
    @CodLocaArmazenagem,
    @CodProduto,
    @CodUnidadeMedida,
    @Quantidade,
    @QuantidadeInterna,
    @QuantidadeExterna,
    @QuantidadeSeparacao
  )