INSERT INTO Expedicao.ItemConferencia(
    CodEmpresa,
    CodConferir,
    Item,
    SessionId,
    Situacao,
    CodCarrinhoPercurso,
    ItemCarrinhoPercurso,
    CodConferente,
    NomeConferente,
    DataConferencia,
    HoraConferencia,
    CodProduto,
    CodUnidadeMedida,
    Quantidade
  )
VALUES (
    @CodEmpresa,
    @CodConferir,
    @Item,
    @SessionId,
    @Situacao,
    @CodCarrinhoPercurso,
    @ItemCarrinhoPercurso,
    @CodConferente,
    @NomeConferente,
    @DataConferencia,
    @HoraConferencia,
    @CodProduto,
    @CodUnidadeMedida,
    @Quantidade
  )