INSERT INTO Expedicao.ItemSeparacaoEstoque(
    CodEmpresa,
    CodSepararEstoque,
    Item,
    SessionId,
    Situacao,
    CodCarrinhoPercurso,
    ItemCarrinhoPercurso,
    CodSeparador,
    NomeSeparador,
    DataSeparacao,
    HoraSeparacao,
    CodProduto,
    CodUnidadeMedida,
    Quantidade
  )
VALUES (
    @CodEmpresa,
    @CodSepararEstoque,
    @Item,
    @SessionId,
    @Situacao,
    @CodCarrinhoPercurso,
    @ItemCarrinhoPercurso,
    @CodSeparador,
    @NomeSeparador,
    @DataSeparacao,
    @HoraSeparacao,
    @CodProduto,
    @CodUnidadeMedida,
    @Quantidade
  )